name: Deployment
on:
    push:
        branches:
            - main

jobs:
    deploy:
        name: CPanel Deploy
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Set up Node.js 24.x
              uses: actions/setup-node@v4
              with:
                  node-version: 24.x

            - name: Install dependencies
              run: npm install

            - name: Build
              run: npm run build

            - name: Show tree
              run: tree

            - name: Rename index file
              run: mv build/index.js build/index.mjs

            - name: Sync
              uses: SamKirkland/FTP-Deploy-Action@v4.3.5
              with:
                  server: ftp.nibli.net
                  server-dir: ./build/
                  local-dir: ./build/
                  dangerous-clean-slate: true
                  username: ${{ secrets.FTP_USERNAME }}
                  password: ${{ secrets.FTP_PASSWORD }}
